version: "3.7"
services:
  app:
    image: kooldev/node:14-nest
    command:
    - npm
    - run
    - start:dev
    ports:
    - ${APP_PORT:-3000}:3000
    environment:
      ASUSER: ${KOOL_ASUSER:-0}
      UID: ${UID:-0}
    volumes:
    - .:/app:delegated
    networks:
    - kool_local
    - kool_global
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - ${FORWARD_DB_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-secret}
      MYSQL_DATABASE: ${DATABASE_NAME:-valenight}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - database:/var/lib/mysql:delegated
    networks:
    - kool_local
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
  cache:
    image: redis:6-alpine
    volumes:
    - cache:/data:delegated
    networks:
    - kool_local
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
volumes:
  database: null
  cache: null
networks:
  kool_local: null
  kool_global:
    external: true
    name: ${KOOL_GLOBAL_NETWORK:-kool_global}
